package com.github.madeindjs.feedID3;

import java.util.HashMap;

/**
 * an HasMap with all ID3 genres maps with corresponding index
 *
 * @see https://de.wikipedia.org/wiki/Liste_der_ID3v1-Genres
 */
public class ID3Genres extends HashMap<String, Integer> {

    public ID3Genres() {
        put("Blues", 0);
        put("Classic Rock", 1);
        put("Country", 2);
        put("Dance", 3);
        put("Disco", 4);
        put("Funk", 5);
        put("Grunge", 6);
        put("Hip Hop", 7);
        put("Jazz", 8);
        put("Metal", 9);
        put("New Age", 10);
        put("Oldies", 11);
        put("Other", 12);
        put("Pop", 13);
        put("Rhythm and Blues", 14);
        put("Rap", 15);
        put("Reggae", 16);
        put("Rock", 17);
        put("Techno", 18);
        put("Industrial", 19);
        put("Alternative", 20);
        put("Ska", 21);
        put("Death Metal", 22);
        put("Pranks", 23);
        put("Soundtrack", 24);
        put("Euro-Techno", 25);
        put("Ambient", 26);
        put("Trip Hop", 27);
        put("Vocal", 28);
        put("Jazz & Funk", 29);
        put("Fusion", 30);
        put("Trance", 31);
        put("Classical", 32);
        put("Instrumental", 33);
        put("Acid", 34);
        put("House", 35);
        put("Game", 36);
        put("Sound Clip", 37);
        put("Gospel", 38);
        put("Noise", 39);
        put("Alternative Rock", 40);
        put("Bass", 41);
        put("Soul", 42);
        put("Punk", 43);
        put("Space", 44);
        put("Meditative", 45);
        put("Instrumental Pop", 46);
        put("Instrumental Rock", 47);
        put("Ethnic", 48);
        put("Gothic", 49);
        put("Darkwave", 50);
        put("Techno-Industrial", 51);
        put("Electronic", 52);
        put("Pop-Folk", 53);
        put("Eurodance", 54);
        put("Dream", 55);
        put("Southern Rock", 56);
        put("Comedy", 57);
        put("Cult", 58);
        put("Gangsta", 59);
        put("Top 40", 60);
        put("Christian Rap", 61);
        put("Pop/Funk", 62);
        put("Jungle", 63);
        put("Native US", 64);
        put("Cabaret", 65);
        put("New Wave", 66);
        put("Psychedelic", 67);
        put("Rave", 68);
        put("Showtunes", 69);
        put("Trailer", 70);
        put("Lo-Fi", 71);
        put("Tribal", 72);
        put("Acid Punk", 73);
        put("Acid Jazz", 74);
        put("Polka", 75);
        put("Retro", 76);
        put("Musical", 77);
        put("Rock ’n’ Roll", 78);
        put("Hard Rock", 79);
        put("Folk", 80);
        put("Folk-Rock", 81);
        put("National Folk", 82);
        put("Swing", 83);
        put("Fast Fusion", 84);
        put("Bebop", 85);
        put("Latin", 86);
        put("Revival", 87);
        put("Celtic", 88);
        put("Bluegrass", 89);
        put("Avantgarde", 90);
        put("Gothic Rock", 91);
        put("Progressive Rock", 92);
        put("Psychedelic Rock", 93);
        put("Symphonic Rock", 94);
        put("Slow Rock", 95);
        put("Big Band", 96);
        put("Chorus", 97);
        put("Easy Listening", 98);
        put("Acoustic", 99);
        put("Humour", 100);
        put("Speech", 101);
        put("Chanson", 102);
        put("Opera", 103);
        put("Chamber Music", 104);
        put("Sonata", 105);
        put("Symphony", 106);
        put("Booty Bass", 107);
        put("Primus", 108);
        put("Porn Groove", 109);
        put("Satire", 110);
        put("Slow Jam", 111);
        put("Club", 112);
        put("Tango", 113);
        put("Samba", 114);
        put("Folklore", 115);
        put("Ballad", 116);
        put("Power Ballad", 117);
        put("Rhythmic Soul", 118);
        put("Freestyle", 119);
        put("Duet", 120);
        put("Punk Rock", 121);
        put("Drum Solo", 122);
        put("A cappella", 123);
        put("Euro-House", 124);
        put("Dance Hall", 125);
        put("Goa", 126);
        put("Drum & Bass", 127);
        put("Club-House", 128);
        put("Hardcore Techno", 129);
        put("Terror", 130);
        put("Indie", 131);
        put("BritPop", 132);
        put("Negerpunk", 133);
        put("Polsk Punk", 134);
        put("Beat", 135);
        put("Christian Gangsta Rap", 136);
        put("Heavy Metal", 137);
        put("Black Metal", 138);
        put("Crossover", 139);
        put("Contemporary Christian", 140);
        put("Christian Rock", 141);
        put("Merengue", 142);
        put("Salsa", 143);
        put("Thrash Metal", 144);
        put("Anime", 145);
        put("Jpop", 146);
        put("Synthpop", 147);
        put("Abstract", 148);
        put("Art Rock", 149);
        put("Baroque", 150);
        put("Bhangra", 151);
        put("Big Beat", 152);
        put("Breakbeat", 153);
        put("Chillout", 154);
        put("Downtempo", 155);
        put("Dub", 156);
        put("EBM", 157);
        put("Eclectic", 158);
        put("Electro", 159);
        put("Electroclash", 160);
        put("Emo", 161);
        put("Experimental", 162);
        put("Garage", 163);
        put("Global", 164);
        put("IDM", 165);
        put("Illbient", 166);
        put("Industro-Goth", 167);
        put("Jam Band", 168);
        put("Krautrock", 169);
        put("Leftfield", 170);
        put("Lounge", 171);
        put("Math Rock", 172);
        put("New Romantic", 173);
        put("Nu-Breakz", 174);
        put("Post-Punk", 175);
        put("Post-Rock", 176);
        put("Psytrance", 177);
        put("Shoegaze", 178);
        put("Space Rock", 179);
        put("Trop Rock", 180);
        put("World Music", 181);
        put("Neoclassical", 182);
        put("Audiobook", 183);
        put("Audio Theatre", 184);
        put("Neue Deutsche Welle", 185);
        put("Podcast", 186);
        put("Indie-Rock", 187);
        put("G-Funk", 188);
        put("Dubstep", 189);
        put("Garage Rock", 190);
        put("Psybient", 191);
    }

}
